// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.9.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api/simple.dart';
import 'api/vtop/client.dart';
import 'api/vtop/parseattn.dart';
import 'api/vtop/parsecoursepg.dart';
import 'api/vtop/parsemarks.dart';
import 'api/vtop/parsesched.dart';
import 'api/vtop/parsett.dart';
import 'api/vtop/types.dart';
import 'api/vtop/wifi.dart';
import 'api/vtop_main.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_IclientPtr =>
      wire.rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerIclient;

  @protected
  Iclient
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerIclient(
    dynamic raw,
  );

  @protected
  Iclient
  dco_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerIclient(
    dynamic raw,
  );

  @protected
  Iclient
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerIclient(
    dynamic raw,
  );

  @protected
  Iclient
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerIclient(
    dynamic raw,
  );

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<RAtCourse> dco_decode_list_r_at_course(dynamic raw);

  @protected
  List<RAttendanceList> dco_decode_list_r_attendance_list(dynamic raw);

  @protected
  List<RMarksCourse> dco_decode_list_r_marks_course(dynamic raw);

  @protected
  List<RTimetable> dco_decode_list_r_timetable(dynamic raw);

  @protected
  List<RscheduleCourse> dco_decode_list_rschedule_course(dynamic raw);

  @protected
  List<RscheduleExam> dco_decode_list_rschedule_exam(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  RAtCourse dco_decode_r_at_course(dynamic raw);

  @protected
  RAttendanceList dco_decode_r_attendance_list(dynamic raw);

  @protected
  RMarksCourse dco_decode_r_marks_course(dynamic raw);

  @protected
  RTimetable dco_decode_r_timetable(dynamic raw);

  @protected
  (bool, String) dco_decode_record_bool_string(dynamic raw);

  @protected
  (bool, String, List<RAtCourse>)
  dco_decode_record_bool_string_list_r_at_course(dynamic raw);

  @protected
  (bool, String, List<RAttendanceList>)
  dco_decode_record_bool_string_list_r_attendance_list(dynamic raw);

  @protected
  (bool, String, List<RMarksCourse>)
  dco_decode_record_bool_string_list_r_marks_course(dynamic raw);

  @protected
  (bool, String, List<RTimetable>)
  dco_decode_record_bool_string_list_r_timetable(dynamic raw);

  @protected
  (bool, String, List<RscheduleExam>)
  dco_decode_record_bool_string_list_rschedule_exam(dynamic raw);

  @protected
  (bool, String, List<String>) dco_decode_record_bool_string_list_string(
    dynamic raw,
  );

  @protected
  RscheduleCourse dco_decode_rschedule_course(dynamic raw);

  @protected
  RscheduleExam dco_decode_rschedule_exam(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  Iclient
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerIclient(
    SseDeserializer deserializer,
  );

  @protected
  Iclient
  sse_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerIclient(
    SseDeserializer deserializer,
  );

  @protected
  Iclient
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerIclient(
    SseDeserializer deserializer,
  );

  @protected
  Iclient
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerIclient(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<RAtCourse> sse_decode_list_r_at_course(SseDeserializer deserializer);

  @protected
  List<RAttendanceList> sse_decode_list_r_attendance_list(
    SseDeserializer deserializer,
  );

  @protected
  List<RMarksCourse> sse_decode_list_r_marks_course(
    SseDeserializer deserializer,
  );

  @protected
  List<RTimetable> sse_decode_list_r_timetable(SseDeserializer deserializer);

  @protected
  List<RscheduleCourse> sse_decode_list_rschedule_course(
    SseDeserializer deserializer,
  );

  @protected
  List<RscheduleExam> sse_decode_list_rschedule_exam(
    SseDeserializer deserializer,
  );

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  RAtCourse sse_decode_r_at_course(SseDeserializer deserializer);

  @protected
  RAttendanceList sse_decode_r_attendance_list(SseDeserializer deserializer);

  @protected
  RMarksCourse sse_decode_r_marks_course(SseDeserializer deserializer);

  @protected
  RTimetable sse_decode_r_timetable(SseDeserializer deserializer);

  @protected
  (bool, String) sse_decode_record_bool_string(SseDeserializer deserializer);

  @protected
  (bool, String, List<RAtCourse>)
  sse_decode_record_bool_string_list_r_at_course(SseDeserializer deserializer);

  @protected
  (bool, String, List<RAttendanceList>)
  sse_decode_record_bool_string_list_r_attendance_list(
    SseDeserializer deserializer,
  );

  @protected
  (bool, String, List<RMarksCourse>)
  sse_decode_record_bool_string_list_r_marks_course(
    SseDeserializer deserializer,
  );

  @protected
  (bool, String, List<RTimetable>)
  sse_decode_record_bool_string_list_r_timetable(SseDeserializer deserializer);

  @protected
  (bool, String, List<RscheduleExam>)
  sse_decode_record_bool_string_list_rschedule_exam(
    SseDeserializer deserializer,
  );

  @protected
  (bool, String, List<String>) sse_decode_record_bool_string_list_string(
    SseDeserializer deserializer,
  );

  @protected
  RscheduleCourse sse_decode_rschedule_course(SseDeserializer deserializer);

  @protected
  RscheduleExam sse_decode_rschedule_exam(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerIclient(
    Iclient self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerIclient(
    Iclient self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerIclient(
    Iclient self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerIclient(
    Iclient self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_r_at_course(
    List<RAtCourse> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_r_attendance_list(
    List<RAttendanceList> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_r_marks_course(
    List<RMarksCourse> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_r_timetable(
    List<RTimetable> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_rschedule_course(
    List<RscheduleCourse> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_rschedule_exam(
    List<RscheduleExam> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_r_at_course(RAtCourse self, SseSerializer serializer);

  @protected
  void sse_encode_r_attendance_list(
    RAttendanceList self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_r_marks_course(RMarksCourse self, SseSerializer serializer);

  @protected
  void sse_encode_r_timetable(RTimetable self, SseSerializer serializer);

  @protected
  void sse_encode_record_bool_string(
    (bool, String) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_record_bool_string_list_r_at_course(
    (bool, String, List<RAtCourse>) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_record_bool_string_list_r_attendance_list(
    (bool, String, List<RAttendanceList>) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_record_bool_string_list_r_marks_course(
    (bool, String, List<RMarksCourse>) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_record_bool_string_list_r_timetable(
    (bool, String, List<RTimetable>) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_record_bool_string_list_rschedule_exam(
    (bool, String, List<RscheduleExam>) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_record_bool_string_list_string(
    (bool, String, List<String>) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_rschedule_course(
    RscheduleCourse self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_rschedule_exam(RscheduleExam self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerIclient(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerIclient(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerIclient(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerIclient(
        ptr,
      );
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {
  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerIclient(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerIclient(
    int ptr,
  );
}
