// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.9.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'types.dart';

Future<List<String>> parseSemidAttendance({required String html}) =>
    RustLib.instance.api.crateApiVtopParseattnParseSemidAttendance(html: html);

Future<List<RAtCourse>> parseAttendance({required String html}) =>
    RustLib.instance.api.crateApiVtopParseattnParseAttendance(html: html);

Future<List<RAttendanceList>> parseFullAttendance({required String html}) =>
    RustLib.instance.api.crateApiVtopParseattnParseFullAttendance(html: html);
