// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.9.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<String> parseSemid({required String html}) =>
    RustLib.instance.api.crateApiVtopParsecoursepgParseSemid(html: html);

Future<String> parseCourses({required String html}) =>
    RustLib.instance.api.crateApiVtopParsecoursepgParseCourses(html: html);

Future<String> parseClasses({required String html}) =>
    RustLib.instance.api.crateApiVtopParsecoursepgParseClasses(html: html);

Future<String> parseDlist({required String html}) =>
    RustLib.instance.api.crateApiVtopParsecoursepgParseDlist(html: html);
