// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.9.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<String> parseSemidMarks({required String html}) =>
    RustLib.instance.api.crateApiVtopParsemarksParseSemidMarks(html: html);

Future<String> parseMarks({required String html}) =>
    RustLib.instance.api.crateApiVtopParsemarksParseMarks(html: html);
