// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.9.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'vtop/client.dart';

// These functions are ignored because they are not marked as `pub`: `login_vtop`

Iclient getClient() => RustLib.instance.api.crateApiVtopMainGetClient();

Future<void> checkClient({
  required Iclient iclient,
  required String username,
  required String password,
}) => RustLib.instance.api.crateApiVtopMainCheckClient(
  iclient: iclient,
  username: username,
  password: password,
);

Future<(bool, String)> onstartRun({
  required Iclient iclient,
  required String username,
  required String password,
}) => RustLib.instance.api.crateApiVtopMainOnstartRun(
  iclient: iclient,
  username: username,
  password: password,
);
